name: namer_app
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_pdfview: ^1.3.4
  dio: ^5.0.0
  url_launcher: ^6.1.4 
  open_file: ^3.5.9
  path_provider: ^2.0.15
  excel: ^4.0.6
  http: ^1.2.2
  intl: ^0.17.0
  csv: ^5.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/prestigelogo.png"


  assets:
    - assets/prestigelogo.png
    - assets/iisclogo.png
    - assets/L&T.png
    - assets/ BESCOM.pdf
    - assets/Airport.pdf
    - assets/Borewell Approval.pdf
    - assets/cfe.pdf
    - assets/cfe1.pdf
    - assets/Conversion Certificate.pdf
    - assets/ENvironmental.pdf
    - assets/FIRE_NOC.pdf
    - assets/SGWA.pdf
    - assets/Borewell_water.xlsx
    - assets/Tanker_water.xlsx
    # - assets/Air_pollution.xlsx
    - assets/Prestige.jpeg
    - assets/IISC_logo.jpeg
    - assets/Tanker_water.xlsx
    - assets/goi.png
    - assets/GOK.png
    - assets/KSPCB.png
    - assets/logo.png
  